### PR TITLE
[HR] Compensation architect

### PR DESCRIPTION
**Pull request by cassus**

### CODE REVIEW

**Comment by peterlangmar** [comment]
:exclamation: This domain seems to be in conflict with the domain of the Guardian of the Galaxy.
:exclamation: Probation time is a contract and as such, it is the domain of the Corporate lawyer [Text of contracts (both internal and external)] and related to the accountabilities of the Legal representative (Negotiating legal documents), moreover it must follow the Labour Code.
:question: I'm not sure I understand the structure of the governance. What is a note? Is it a policy? Why have you introduced this new structure for the domain?

**Comment by cassus** [comment]
@peterlangmar how about now?

**Comment by peterlangmar** [comment]
Better, but still a few points:
:exclamation: The "Employee/Partner compensation" domain is still in conflict with the domain of the Guardian of the Galaxy.
:question: " Proposing changes to the Ownership system" So this role is not accountable to implement the agreed changes?
:question: Why do you connect peer reviews and compensation system?

**Comment by cassus** [comment]
> The "Employee/Partner compensation" domain is still in conflict with the domain of the Guardian of the Galaxy.
These are domains of the HR circle in TLC. I'm exactly aligning with those:
- Employee/Partner compensation
- Salary system and peer-reviews

> Proposing changes to the Ownership system" So this role is not accountable to implement the agreed changes?
Not specified

> Why do you connect peer reviews and compensation system?
Now in my practice they are connected. We can separate later if needed

**Comment by cassus** [comment]
No update for months. Bring again if still not resolved.

**Pull request closed without merging**
