### PR TITLE
Policy: Car usage

### PR DESCRIPTION
**Pull request by banyomarci**
##Tension: Cost reinmbursement for business trips by car is not clear

### CODE REVIEW

**Comment by peterlangmar** [comment]
How should I calculate the petrol cost? What is I have a yearly highway allowance?

**Comment by banyomarci** [comment]
1. Petrol cost calculation formula; used petrol * price of petrol :) In case of private car usage, agreed with finance role we won't report to NAV so there is no official formula. Lab trusts you. 
2.  Good question. Yearly fee / 365 * # of days of your business trip could be a solution.

**Comment by kire321** [comment]
This is an issue between you as a person and the company, and doesn't belong in governance. You can bring this issue to the Tribal RL instead.
:exclamation: NVGO: policies are not created / modified via governance

**Comment by banyomarci** [comment]
Erik, it's not a personal issue, it belongs to my role as EMS LL and we have a policy about cost reinmbursement but it was not clear enough. So I want to make it clear.

**Comment by banyomarci** [comment]
@cassus

**Comment by cassus** [comment]
@banyomarci as EMS role asked me to interpret the constitution on what is an NVGO


### I quote 3 parts of the Constitution that relate to this case
As I believe you are not familiar with these parts and it helps to frame what Banyo asked and what I'm doing.

> **3.4 Interpreting the Constitution & Governance**
> 
> As a Partner of the Organization, you may use your reasonable judgment to interpret this Constitution and any Governance within the Organization, including how these apply within a specific situation, and then act based on your interpretation. You may also rely on an explicit interpretation given by the Secretary of any Circle that is affected by the Governance. However, in either case, the following additional terms apply:
> 
> **3.4.1 Secretary Interpretation Trumps**
>  
> If your interpretation conflicts with an interpretation ruling made by a Secretary, the Secretary’s interpretation trumps your own and applies instead, and you are responsible for aligning with it until any underlying Governance changes.

> **3.2.5 Testing Objections**
> [...]
> However, when an Objection is claimed on the basis of a Proposal violating the Constitution, per Section 3.2.4(e), the Facilitator may ask the Circle’s Secretary to interpret if the Proposal does indeed violate the Constitution. If the Secretary rules that it does not, the Facilitator must then dismiss the Objection.



### And here is my Secretary interpretation

> Compensation in case of business trip by private car; petrol and highway cost + 9Ft/km (NAV standard) for amortization. Cost reinmbursement happens through splitwise

**Secretary interpretation**: Any Role may spend company money on business trips by private car if you file the cost for reimbursement on Splitwise. You may spend on the the amortization of the private car at the rate of 9Ft/km, and on petrol and highway allowance.

**Secretary NVGO interpretation**: Valid governance, this allows Roles to spend company money. (It's secondary that the resource used is private)

> Compensation in case of renting a car for business trip; max rental  + km fee + petrol and highway cost. If it's possible get invoice, if not, cost reimbursement happens through splitwise

**Secretary interpretation:** Any Role may spend company money on business trips by rented car. You may spend up to cost 20EUR/day on rental, and on petrol and highway allowance. Note: please try to get an invoice

**Secretary NVGO interpretation**: Valid governance, this allows Roles to spend company money. (It's secondary that a partner can pay from their personal money an later get that back from the company)


> Our prefared car rental service is beerides.com

**Secretary interpretation**: Note: beerides.com is a prefferred car rental service
(A Policy is: _either grants of authority that allow others to control or cause a material impact within a Domain, or limits on how others may do so when otherwise authorized_)

**Secretary NVGO interpretation**: As of now there is no good way to store these notes, so I'll say it's okay to reside next to a Policy

> Let financial role know about your car usage prior your travel if it's possible

**Secretary interpretation**: _if it's possible_ makes it a void Policy.
**Secretary NVGO interpretation**: As above with Notes

> Provide invoice of the car expenses to the finance role at the latest 3 workdays after return

**Secretary interpretation**: Void, (A policy may not require or prescribe action). This could be a note. (Expecting a deadline would set priorities and that is not valid governance. )

**Secretary NVGO interpretation**: As above with Notes

> The company is not liable for damages of the private car
> The company is not liable for caused damages
> The company is not liable for fines

**Secretary interpretation**: as policy void, this could be a helpful or misleading note. An Interpretation of the employment agreement for the cases where an employee causes damages or fines. (As TLC Secretary I'm not ruling whether this is an accurate interpretation of the Employment contract.)

**Secretary NVGO interpretation**: As above with Notes

**Comment by cassus** [comment]
As Holacracy Coach role:
I invite all of you to come to the _holacracy coach office hours / lunch_ on Friday. I can give you many more details and tips related to this topic.

**Comment by kire321** [comment]
Ok, I think I understand...
Roles can unilaterally modify policies on their domains
Circles modify their policies via governance

**Comment by peterlangmar** [comment]
I'm glad for the in-depth meta discussion and the theoretical learning, but what I can also see here is the Partners still being blocked from properly reimbursing their car travel costs. If such a small and pretty trivial update in our governance can not go through in a month (!), than we are in trouble. Imagine an important update, which has significant impact on the business... In this case the processes are blocking us to get stuff done and turning off the proposer might not be the right way. We need better holacracy implementation and common sense now. @cassus and @kire321 these are exactly the cases I've discussed with you.
@banyomarci I hope you will have the courage to get back with this proposal :)
Today, I'm travelling to Siófok by car. I've decided to  get reimbursement based on this policy proposal.

**Comment by cassus** [comment]
> In this case the processes are blocking us to get stuff done
> Today, I'm travelling to Siófok by car. I've decided to get reimbursement based on this policy proposal.

I don't see any agreement that would limit you from doing that.

I sense a misunderstanding about what governance is necessary for doing stuff. This would be a great topic for the next _holacracy coach office hours_

> banyomarci I hope you will have the courage to get back with this proposal :)
👍 

> turning off the proposer might not be the right way.
I agree. I had some discussion with a UK Holacracy coach about this and I believe I arrived to a more balanced perspective.

**Comment by peterlangmar** [comment]
Was it worth, that this has been blocked?

**Comment by cassus** [comment]
Tell me if you need help processing your tension about "this has been blocked"

**Comment by peterlangmar** [comment]
@cassus good idea, please, help me with this tension I feel

**Comment by cassus** [comment]
No update for 2 months. I close this pull req. Feel free to re-open it if you want to move it forward.

**Pull request closed without merging**
