### PR TITLE
updating purpose

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: lots of confusion around purpose. We have started an agency, which we are using to finance other business brunches too. It is important to distinguish between the agency's, the other business branches' and LabCoop's (as an umbrella) purpose.

### CODE REVIEW

**Comment by cassus** [comment]
This makes it less clear for me what purpose to align with.

Let's resolve this in gov meeting
:exclamation:

**Comment by ikocse** [comment]
@cassus I think the alignment should not be defined on personal level, its much rather about to define the standalone business branches and the relation between those branches, this should bring actually more clarity on company level

**Comment by nagydan1** [comment]
Maybe mention clients in the agency part.
I'm also looking forward to a personal discussion on the gov meeting tomorrow.

**Comment by peterlangmar** [comment]
Client = owner for me

**Pull request merged**
