### PR TITLE
Recruiter rename to HR Selection

### PR DESCRIPTION
**Pull request by peterlangmar**
recruitment (like having HR leads) is more an evangelist accountability (that role has been updated accordingly)
selection is what this role really does
added some accountabilities and domains

### CODE REVIEW

**Comment by cassus** [comment]
You removed the Employee handbook editor role!

**Comment by peterlangmar** [comment]
@cassus thanks for realizing. fixed.

**Comment by cassus** [comment]
I'd like to keep the Recruiter role, as it's live and Aniko and Juli is working in it.
I also prefer to have your Recruitment related Evangelism (also) in this role, so roles working towards the HR purpose are in the HR circle.

I also like your proposal of HR Selection role, as a new role.

**Comment by peterlangmar** [comment]
Well, in my understanding this is the opposite of what we have agreed at the walking meeting, so I guess we did not really understand each other. #confusion 

In this case I'd keep the name, would not make new roles and still would suggest the domains and accountabilities which I've suggested

**Pull request merged**
