### PR TITLE
Hardware Accelerator role

### PR DESCRIPTION
**Pull request by peterlangmar**
tension: I've been already doing this for a while

### CODE REVIEW

**Comment by cassus** [comment]
Investment to Hardware Accelerator -- what is that domain about?

**Comment by peterlangmar** [comment]
investing money to the HWACC
I'm not sure I've got your question....

**Comment by cassus** [comment]
So the Finance/Biz and the Hardware Accelerator both decide in their domain about investment? That seems contradictory

**Comment by peterlangmar** [comment]
thanks @cassus I've got your point, nice catch! I've fixed

**Pull request closed without merging**
