### PR TITLE
partner handbook

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: there are already great resources, but it is hard to find them and to consume them as a whole. Both new and existing partners lack the information sources while on-boarding / being stuck.

Context: even just having a list of link would be a step forward
These are great examples
http://handbook.enspiral.com/
http://www.valvesoftware.com/company/Valve_Handbook_LowRes.pdf

### CODE REVIEW

**Comment by cassus** [comment]
I'd like to better understand the tension.
Please bring to governance. ❗

**Comment by cassus** [comment]
as I understand the target group is partner candidates
this would be like a public employee handbook
purpose is stronger employer brand, company intro

- Governance
- Co-ownership prezi
- Important processes
- Company structure / GreenFox

(not admin/mundane stuff)

**Comment by peterlangmar** [comment]
@nagydan1 this accountability might be a better fit for Marketing Circle, or at least it is "thing" between Marketing and PP circles

**Comment by peterlangmar** [comment]
@cassus do you still want me to bring it to governance or has your objection been resolved?

**Comment by cassus** [comment]
💥  Governance please

**Pull request closed without merging**
