### PR TITLE
delete mome code

### PR DESCRIPTION
**Pull request by peterlangmar**
training is over

### CODE REVIEW

**Comment by hubudibu** [comment]
:exclamation: we have not yet been paid, we don't have signed contracts and we will most likely have our next class in the spring/summer which is under development

**Comment by peterlangmar** [comment]
@hubudibu ok, sorry, I have thought that it is over. I wont go further with this change until you confirm

**Comment by peterlangmar** [comment]
the paperwork is ready, they have paid
@hubudibu should we keep it as it is restarting or can we delete it?

**Comment by hubudibu** [comment]
there is an ongoing project, if you are interested in the status see asana, also can we please not do this every 2 weeks? I'm having a hard time understanding your intentions here

**Comment by peterlangmar** [comment]
My intention and need is transparency. As there is no contract on the table, from my legal and biz role there is no project. Now I can see, that you work on this ongoing, so I'm deleting my pull request.

**Pull request closed without merging**
