### PR TITLE
[Company purchases] Partners can't combine their budgets

### PR DESCRIPTION
**Pull request by cassus**
eg. for buying wifi fixing service and hardware

### CODE REVIEW

**Comment by cassus** [comment]
@peterlangmar this came up talking about if we could decide on the wifi services without you. I'm not sure if this would be still safe to fail, please object if not.

**Comment by peterlangmar** [comment]
!
I have to disagree. This would mean that a bigger number of partners can buy basically pretty expensive stuff without discussing the budget. The biz role has domain over the budget. This would make my life hard and the idea is not safe to fail.

**Comment by cassus** [comment]
@peterlangmar integrated your objection.

**Comment by peterlangmar** [comment]
So basically this proposition has been withdrawn. Thanks!

**Comment by peterlangmar** [comment]
merge please

**Pull request merged**
