### PR TITLE
Comp clarification + "family option"

### PR DESCRIPTION
**Pull request by cassus**
Tension from Recruiter role: Previously I have lost multiple ppl as family ppl are more sensitive to comp reduction

### CODE REVIEW

**Comment by peterlangmar** [comment]
!

**Comment by cassus** [comment]
@peterlangmar as TLC Biz with the domain of `All company budgets` as there is no other process for the authorization of a change of an ongoing budget, please approve this change.

**Comment by cassus** [comment]
@peterlangmar I see in your cal that tomorrow you'll be on Holiday and not attend the PP governance. I'm curious if you have any more specific reflection on this proposal

**Comment by peterlangmar** [comment]
@cassus I have questions in general and from my domains in biz and guardian of the galaxy. I'll try to call you today

**Comment by cassus** [comment]
@peterlangmar as Biz agreed over the phone to allocate the needed resources to this 
(I'll think of a better place to store resource allocation agreements)

**Pull request merged**
