### PR TITLE
PO role accountabilities

### PR DESCRIPTION
**Pull request by peterlangmar**
sales (or tlc lead link...) has been doing lots of work with the client

### CODE REVIEW

**Comment by EggDice** [comment]
I don't know what is the process if you want something like this.

**Comment by peterlangmar** [comment]
me either, but now way I'll handle this work in the future

**Comment by EggDice** [comment]
I guess you have to add it as a Emarsys circle accountability, from the product circle governance.

**Comment by peterlangmar** [comment]
have added there too thanks

**Comment by EggDice** [comment]
cool!

**Comment by EggDice** [comment]
Also add the product circle tag to the pull request's name

**Comment by peterlangmar** [comment]
done

**Pull request closed without merging**
