### PR TITLE
dishwasher

### PR DESCRIPTION
**Pull request by nagydan1**
In the sake of eco-consciousness only start the dishwasher whenever it is full. Starting it every day with a few plates is a waste.

### CODE REVIEW

**Comment by peterlangmar** [comment]
What is your proposition to make sure that we have enough dishes and space in the dishwasher every day?

**Comment by cassus** [comment]
I'm glad this discussion is happening. I had trouble deciding on this before :)

**Comment by peterlangmar** [comment]
I fell my time is being wasted here both by cleaning the office and by discussing for hours thigs which could be common sense.

**Comment by nagydan1** [comment]
Discussing this is clearly a waste of time. If there is objection I am happy to let this go.
But answering your question: we have enough plates anyway... I just unpacked the dishwasher today and didn't last for 10 seconds cos it was loaded less than 25%. Just seemed a waste...

**Comment by peterlangmar** [comment]
Please, come up with a proposition which will decrease more the dust, the pile of dirty dishes and would waste less of my time. And this is a discussion.

**Comment by cassus** [comment]
Oops.. reopen.

**Comment by cassus** [comment]
I resolved the merge conflicts

**Pull request merged**
