### PR TITLE
legal decisions

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension from my Legal rep role: when Partner Agreement Steward role has got the domain over Member Grant Agreements, than the Legal rep role is blocked, it is not legally safe for the company.
Extra nice thing: I'm still personally responsible...

### CODE REVIEW

**Comment by cassus** [comment]
Partner Agreement Steward role hasn't got domain over Member Grant Agreements

So I think the tension is based on a misunderstanding ❓

**Comment by kire321** [comment]
:exclamation: I cannot judge which decisions have legal implications. This would force Visibl dev and PP circle to ask the legal representative role before making any decision.

It would solve my tension to list out which decisions have legal implications, so that all other decisions are allowed.

**Comment by peterlangmar** [comment]
@kire321 Well, you should ask the legal role, this is the point, as the law is above all and above holacracy. The list would be all the Hungarian laws and our contracts.

**Comment by cassus** [comment]
Sounds like you want to go for a whitelisting of decisions that can be taken without CEO approval.

**Pull request merged**
