### PR TITLE
CSR

### PR DESCRIPTION
**Pull request by peterlangmar**
I want to build a socially a responsible company. Internally we could not proceed yet, so now I'm trying to make progress externally. The two could work well together!

### CODE REVIEW

**Comment by cassus** [comment]
nice! :+1:

**Comment by hubudibu** [comment]
:+1: :heart: :yellow_heart: :purple_heart:

**Comment by nagydan1** [comment]
:+1: This is cool

**Comment by hubudibu** [comment]
context: we use https://hashtagcharity.org/ with the momecode team to use our skills for charity, we could do an internal workshop with that sometimes if anyone else is interested

**Pull request merged**
