### PR TITLE
circle accountability updates

### PR DESCRIPTION
**Pull request by peterlangmar**
these things kept falling back on sales / lead link which is a huge overhead for me
I work weekly 0.5-1 days on EMS and Visibl, which is not my role

### CODE REVIEW

**Comment by banyomarci** [comment]
:exclamation: these accountabilities are not connected to the PO role. It is a sales activity and has to be the accountability of a new "account" role.

**Comment by peterlangmar** [comment]
ok, I see and I can agree
however, this policy does not says that these  accountabilities should go for the PO role
it is up to the circle to decide, who (maybe the LL) takes care of it
I do not think I need to change the policy.

@banyomarci do you have any problem with the wording of the policy?

**Comment by banyomarci** [comment]
Sorry I copied my comment from previous pull request and the branch name is po-update. :+1:

**Comment by peterlangmar** [comment]
so it is good to go on @banyomarci 's side

**Comment by peterlangmar** [comment]
@cassus How would you add this accountability in a way that we do not need to copy paste it to each and every client circle's accountabilities?

**Comment by cassus** [comment]
I don't have a ready solution for that.
I'm also not sure that this is a problem to fix, but I'd like to discuss this on the Holacracy Learning meetings.
I'm okay with the way it is now.

**Comment by peterlangmar** [comment]
@cassus ack

**Pull request merged**
