### PR TITLE
hr circle

### PR DESCRIPTION
**Pull request by peterlangmar**

### CODE REVIEW

**Comment by cassus** [comment]
:exclamation: _Ownership system (once every 3 months)_ is unclear as a domain.

**Comment by peterlangmar** [comment]
@cassus clearer now? or should I move it to a policy?

**Comment by cassus** [comment]
Yep, it's a domain and a restriction (Policy) baked into one, splitting them would turn this into valid governance output.

**Comment by peterlangmar** [comment]
@cassus where would you make that policy? in tlc? where to put it?

**Comment by cassus** [comment]
Under the same named domain in TLC to make it easy to find.
Also I'd name the delegated domain: _Ownership system (with limitations)_ to make it clear it's limited by policies in a parent circle.

**Comment by peterlangmar** [comment]
@cassus I see your point, but I'm not sure I can make the change properly. Could you help me out, so I can learn it for the future?

**Comment by cassus** [comment]
My idea is to do something like:

```
Domains:
- Ownership system (with limitations)
[...]
# Domains
## Domain: Ownership system
### Policy: Ownership system update frequency
[...]
```

**Comment by cassus** [comment]
good to go!

**Pull request merged**
