### PR TITLE
[HR] Interviewer role

### PR DESCRIPTION
**Pull request by cassus**
Tension: we work in these roles, let's give it a name and an initial purpose so we can iterate.

### CODE REVIEW

**Comment by peterlangmar** [comment]
@cassus I conduct quite some interviews. Possibly I conduct most of them.

**Comment by cassus** [comment]
Yep, the boundary between the Recruiter and Interviewer is somewhat unclear. These people have a focus are to interview for, and you kinda do general interviewing / introductions which is still covered by the Recruiter role.

**Comment by peterlangmar** [comment]
I see your point, but I can not differentiate between the roles. At this point I'd merge the roles or would clearly separate the domains and accountabilities. I share your tension, but this new role wont solve it.

**Comment by cassus** [comment]
It solves my tension of giving focused accountabilities to the other people who don't to recruitment but only interviewing. I'm okay if this doesn't yet solve other tensions or your similar tension.

**Comment by peterlangmar** [comment]
ack
This is the case of Tojas, right?

**Comment by cassus** [comment]
Yes, mainly Tojas, with the focus of Dev skills.

Me and Juli are in both roles now and I'd like to iterate further with these roles so the distinction is more clear.

**Comment by EggDice** [comment]
So are you agreed? Can I merge it?

**Comment by cassus** [comment]
There was no objection, only context.

**Pull request merged**
