### PR TITLE
third party licenses

### PR DESCRIPTION
**Pull request by peterlangmar**
We and or clients have a high legal risk here.

### CODE REVIEW

**Comment by kire321** [comment]
This PR requires work to be done but doesn't assign it to anyone, so probably no one will do this. Maybe you could assign an accountability to a role/circle instead, and then specific people know they are supposed to do this?

:exclamation: In its current form, this proposal makes our problem of policy spam even worse, discourages me from paying attention to policies and governance.

**Comment by peterlangmar** [comment]
@kire321 I'have already asked @cassus' help to advise me about this accountability / policy. Where to put this etc, so I totally see your point.

Regarding the tension: at the strategy meeting, Felhő shared some of the learning of the due diligence process of Ustream. It turned out to be a huge legal liability. I've realized that we are legally not fully safe (or at least we are not sure about it). From my Stroman role I need to take responsibility for this.

**Comment by cassus** [comment]
My guess is that these different parts are tangled in your one policy proposal:
- Client circles accountability: Maintaining a list of all used third party source codes and services and their licence conditions.
- TLC Policy: Only use third party source code or service if you are sure it's legal for the project. Check with Legal when in doubt.
- Legal Accountability: Guiding decisions whether a certain code or service is safe to use in a project on request
- Legal Accountability: Publishing and Maintaining a guideline on what licenses are safe to use in our projects

**Comment by peterlangmar** [comment]
@kire321 do you still object?

**Comment by kire321** [comment]
Yes, my objection still stands.

**Comment by peterlangmar** [comment]
@kire321 please elaborate so I can integrate

**Comment by cassus** [comment]
It's also a valid objection online to just take it to a governance meeting.

**Pull request merged**
