### PR TITLE
Changed timetracking policy

### PR DESCRIPTION
**Pull request by banyomarci**

### CODE REVIEW

**Comment by peterlangmar** [comment]
:+1: 

Company wide? Can you clarify @banyomarci ?
Context: this is a new task for Tech Support @Jeszi

**Comment by cassus** [comment]
Related task: https://app.asana.com/0/39720954602441/35681943756422

**Comment by cassus** [comment]
What is the tension? Felt in which role? (It might be @peterlangmar he wrote "not having this tool really hurts my daily work")

What is the required precision?  Do we need to make sure it's accurate up to a half hour? A half day? 1/10th of a week? Which required precision would solve the tension?

Am I right that: This doesn't include the need to track time per task or per project. That's still up to the person.  :question:

**Comment by cassus** [comment]
Is it important to differentiate between time spent on my HR LL and OrgDev? What tension drives the need to track with such granularity?

:exclamation: accepting this proposal as is would create many tensions around the clarity of my roles. I'm a bit skeptical that the effort required to clarify and differentiate all our roles is all needed to resolve the tension behind proposing time tracking.

It's good to clarify roles, as tensions arise about them in the day to day work, not for the sake of tracking time.

Don't get me wrong, I keep track of most of my time for my own awareness and self-improvement and I think it's a good thing. But we should find ways to mindful about our collective efforts that creates more value than overhead.

**Comment by cassus** [comment]
Time tracking is such a powerful tool I'm afraid to introduce it's use with 2 sentences in a policy. I'd like to be more precise about it. And sure we should iterate on it.

**Comment by peterlangmar** [comment]
Facts about this policy
1. This policy has been submitted on the 26th, so @nagydan1 should have already merged it. Please, do not break the async policy just because the secretary was late.
2. Related task - finally Banyó M and Aniko have made their research and decision: Toggl. Basically this is why @banyomarci started to update this policy, which is not new, has already exist.

Reflections to @cassus questions
My tension? We can see the dedicated time to each client project role (as we already have time tracking for invoicing), but we do not know how much time each internal role requires. I need this info as LL, as a person working mostly in internal roles, as a recruiter and as the biz role.
"Can I hire an additional admin person? Why?" "Should we hire a recruiter as Cassus need more time for OrgDev?" These questions can be answered easily with time tracking. Due the above it is important to differentiate between roles.

"Don't get me wrong, I keep track of most of my time for my own awareness and self-improvement and I think it's a good thing. But we should find ways to mindful about our collective efforts that creates more value than overhead." I agree. This is why we have made this policy.

**Comment by cassus** [comment]
Sorry, for breaking our async policy. Treat my comments as context.

**Comment by peterlangmar** [comment]
@cassus I have already started to try to amend some of your comments, so at this point lets try to come up with something we can all live with.

**Comment by cassus** [comment]
@peterlangmar if you need info about me resource allocation I can tell you, no need to wait weeks for data to accumulate in Toggle

**Comment by peterlangmar** [comment]
go ahead and let us know! I'm keep on to know your recruiter, orgdev, visibl ratios and the whatever leftover

**Comment by cassus** [comment]
Visibl: 15-25h
OrgDev: 20-30h
Recruiter: 0-6h

**Comment by peterlangmar** [comment]
:+1:

**Comment by cassus** [comment]
@banyomarci Petak took your initiative, we accepted with changes, pls check.

**Pull request merged**
