### PR TITLE
holiday restriction

### PR DESCRIPTION
**Pull request by peterlangmar**
whole team on holiday at the same time caused client conflict

### CODE REVIEW

**Comment by nagydan1** [comment]
:question: How should we get sickleaves pre-approved? Does this mean that if I have an approved holiday and someone gets sick and the client freaks cos someone suddenly gets sick I should cancel my holiday?

**Comment by peterlangmar** [comment]
@nagydan1 On one hand an operation, dentist etc can be preplanned. On the other hand I've made some clarifications

**Comment by nagydan1** [comment]
:exclamation: "might need to be broken" is vague, either break it or not.
:question: Do we let clients know this?

**Comment by peterlangmar** [comment]
@nagydan1 
regarding :exclamation: fixed
regarding :question: These policies are public, so yes. Moreover, I've added some clarification based on your feedback.
In the long run, it would be great to manage this (and some other stuff, like high prio bugs) in the HowWeWork, which is an Annex of the contract.

**Pull request merged**
