### PR TITLE
office security

### PR DESCRIPTION
**Pull request by peterlangmar**
tension: there are events at the office, which invite external people to our office space (for example the Pride this weekend), which needs to be prepared from the security point of view

### CODE REVIEW

**Comment by cassus** [comment]
Sounds like a part of the purpose
Could also be an accountability if you specify what ongoing action you look for

screen shot 2016-06-29 at 10 12 39

**Comment by peterlangmar** [comment]
@cassus thanks, this table is pretty useful. Is your suggestion to turn my proposal into a purpose?

**Comment by cassus** [comment]
to update the purpose

eg: Perfect office: happy partners and secure work environment

**Comment by cassus** [comment]
👍

**Pull request closed without merging**
