### PR TITLE
naming convention

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: I've been asked several time about the CEO / Founder / Partner / Owner bla bla bla naming conventions of our org, but there is no clear answer. We need a logic, which makes it clear for the external word or roles in the org.

Solution: taking the best practice of consulting (like big4) and law firms, which make the seniors 'partners' with a buy-in option. The term Partner fits both with common sense business language and with holacracy. Managing partner is not perfect, but is my best guess, and is better than CEO. Lets be realistic, as we still need something CXO-ish for the external world, outside of our bubble... #communications

### CODE REVIEW

**Comment by cassus** [comment]
:exclamation:

**Comment by cassus** [comment]
Now I'm fine you using the term CEO

**Comment by nagydan1** [comment]
:question: Who is considered a LL that can use managing? Only TLC or sub-circle LLs too?

**Comment by peterlangmar** [comment]
@nagydan1 clarified

**Comment by nagydan1** [comment]
cool

**Comment by cassus** [comment]
What does this apply to? LinkedIn? Discussions? Business cards? Company website?

**Comment by peterlangmar** [comment]
@cassus yes exactly. I've updated the proposal

**Comment by cassus** [comment]
typo in "publis appreance"

**Pull request closed without merging**
