### PR TITLE
Partner Agreement process

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: there is no such thing yet, which hurts a lot

### CODE REVIEW

**Comment by kire321** [comment]
:question: What role feels this tension?

**Comment by peterlangmar** [comment]
TLC LL, evangelist, recruiter, sales

**Comment by kire321** [comment]
:question: 

TLC LL -- this role is in the TLC. You could ask the PP LL to represent this tension in the PP circle
evangelist -- How does the lack of partner agreements reduce the evangalist's capacity to fullfill it's purpose or accountabilities?
recruiter -- I see you don't fill the recruiter role currently. Has the recruiter asked you to process a tension on their behalf?
sales -- this role is in the TLC. You could ask the PP LL to represent this tension in the PP circle

**Comment by peterlangmar** [comment]
@kire321 welcome back rule commander...
@cassus please clarify, if I have a role in PP, as you keep inviting me to PP gov and tactical meetings, so this is the impression you make. If I'm not, than I need to ask you to make me a recruiter, as I do work in this field

**Comment by cassus** [comment]
You hold Facilitator, Partner Evangelist, Interviewer (focus: Biz skills) and Immigration role in the PP circle.

**Comment by peterlangmar** [comment]
thanks @cassus

**Comment by cassus** [comment]
accepted in governance

**Pull request closed without merging**
