### PR TITLE
[TLC] Secretary accountability to merge the async pull requests

### PR DESCRIPTION
**Pull request by cassus**
Clarification. It was already part of the Async policy

### CODE REVIEW

**Comment by peterlangmar** [comment]
:+1:

**Comment by peterlangmar** [comment]
:+1: 

My ps to all of these accountability changes: to make it clearer, we should add this to the TLC asyn policy instead of into each secretary accountability. @cassus what do you think?

**Comment by nagydan1** [comment]
:question: Is it still OK to not monitor async requests every day, but rather in bulks once a week, making sure that there is no pull request left for the gov meeting, that should have been already merged?
Context: I see your point and aware the mini-conflict of Cassus objecting a policy that should have been already merged. So far I took care of these once a week, preferably before the gov meeting so they do not go on the agenda.

**Comment by peterlangmar** [comment]
I think taking care of it once a week is ok. However, the late-merge should not meant that the policy can be blocked.

**Comment by cassus** [comment]
If something is an accountability, let's list it at the roles's accountabilities, not inside some policy. This is more explicit. It's also referred in the policy.

**Comment by peterlangmar** [comment]
ok, just this way we will need to copy past and maybe change it in each and every circle, which uses async policy

**Pull request merged**
