### PR TITLE
only sales can make official offers + sales process

### PR DESCRIPTION
**Pull request by peterlangmar**
tension: Dani and Dani have made an offer without checking with resource clarity or sales, which we could not deliver

### CODE REVIEW

**Comment by peterlangmar** [comment]
@kire321 @cassus et all, this is a draft, which some roles are still working on

**Comment by peterlangmar** [comment]
I need your input: @ikocse @banyomarci @judikdavid @golya @EggDice @adamgyulavari @nagydan1 @julimata 
If needed, I'd be glad to arrange a topic meeting before bringing this to governance. Thanks!

**Comment by hubudibu** [comment]
does this mean that you want to 💥 bring it to governance and not have it async merged?

**Comment by peterlangmar** [comment]
No, this only means that I'm looking for input. If there is no input, than async is ok for me

**Pull request merged**
