### PR TITLE
company invoice tracking

### PR DESCRIPTION
**Pull request by peterlangmar**

### CODE REVIEW

**Comment by cassus** [comment]
this will create double-tracking with https://docs.google.com/spreadsheets/d/1n1xfIGBuBe1IAIjhP-SUL0LrzrLgYIjZm2XaaFaV-rY/edit#gid=0

**Comment by peterlangmar** [comment]
@cassus you are right. At the moment this policy will save us time and secure our financial operations, so it is  progress. Once we have someone, who oversees all our financial processes than these could be merged. At the moment I do not have resources for this...

**Comment by peterlangmar** [comment]
@cassus I've made a task for this https://app.asana.com/0/33571529181923/68069218561227

**Comment by cassus** [comment]
Thank you!

**Pull request merged**
