### PR TITLE
calendar modification

### PR DESCRIPTION
**Pull request by peterlangmar**
I repeatedly waste time by not being able to make edits to events.

### CODE REVIEW

**Comment by cassus** [comment]
:exclamation: let's talk about this on governance meeting

**Comment by nagydan1** [comment]
Accepted at gov meeting 15.1.2016. Resolve conflict!!

**Comment by banyomarci** [comment]
Sorry for off topic, maybe I'm noob, but how to share my cal to edit with everyone? I can add people only one-by-one.

**Comment by cassus** [comment]
Same here

**Pull request merged**
