### PR TITLE
limit home office

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: it has a negative impact on the community, inter-Partner relationships and communications not meeting and being in touch with some of the partners even for weeks. Would be great to meet at least once in a while in the office

### CODE REVIEW

**Comment by kire321** [comment]
I include this in the first version of Partner Agreements, and remove it from here when the first version of partner agreements is agreed

**Comment by peterlangmar** [comment]
:+1: @kire321 

context: there are several proposals, which would be moved to partner agreements, but right now there is no better place for them than the governance. >> this is why there is a proposal about the partner agreement development process too :)

**Comment by golya** [comment]
Why 2 days? And I am not sure that if you limit this then it will solve the problem with the community.

**Comment by peterlangmar** [comment]
3 days together would be a step forward for me, which I'd be glad to experiment with. However @golya, I'm open for other ideas!

**Comment by hubudibu** [comment]
💥 please bring it to governance

**Comment by peterlangmar** [comment]
@hubudibu sure, lets cover this on governance.

Note: however, if I'd be a szabálynázi than I would just merge this proposal as it is, because I've made the pull request 7 days ago and there was no comment blocking me merging.

**Pull request closed without merging**
