### PR TITLE
partner loan

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: I've been asked several time, if the company could give a loan to Partners in special situations This is an unregulated area at our org, but the law allows employers to provide loans to their employees.
Solution: Lets make this part of our benefits. Yes, the company can help out the Partners with small and short run liquidity issues.

### CODE REVIEW

**Comment by cassus** [comment]
:exclamation: This would hurt recruitment

**Comment by peterlangmar** [comment]
@cassus hmm sure, than I'll bring it to governance, it was not my intention to hurt recruitment. However, I have no idea, how it could hurt recruitment. Is it a good fix to only enable this after the probation period?
I've also clarified the Tension explanation, see above

**Comment by ikocse** [comment]
taxation background: in case we are providing a loan, we have to charge interest (MNB+5%) to the employee, otherwise the non charged interest is to be considered as taxable income to the employee

there is an option to provide salary advance which is free of tax if the partner pays back within 6 months from the salary (in this case dividend is not applicable) and the amount doesn't exceed the  actual minimum salary multiplied by 5. 

We should also consider that in case we provide such a loan or salary advance, the net income of partners in the "non dividend months" will be significant low. 

therefore I suggest to maximize the amount of such salary advances in HUF 300.000.

detailed description in Hungarian below:
http://ado.hu/rovatok/ado/munkabereloleg-vagy-munkaltatoi-kolcson

**Comment by cassus** [comment]
Thanks @ikocse for the additional info! Many things I didn't know.

If Finance role gets a domain over "Partner loan", he can define policies on that domain without governance. I'd love to see that happen. Governance is good at clarifying and evolving expectations and the rules of working together. This is more of an expert matter, that is best if a Role decides and regulates.

**Comment by peterlangmar** [comment]
accepted at TLC, but merge conflict
please merge @cassus

**Comment by EggDice** [comment]
Wow, interesting and cool conversation, It is quite amazing to see this! :)

**Pull request merged**
