### PR TITLE
[WIP] Advice process for companyWide meetings and fail-safes for it in TLC

### PR DESCRIPTION
**Pull request by cassus**
Tension: It's getting increasingly painful and slow to find consensus with all partners in companyWide meetings and this will only get worse as we grow. We need a different way to make decisions that affect many people.

### CODE REVIEW

**Comment by cassus** [comment]
Why isn't holacracy good for companyWide decisions?


Because holacracy governance depends on
1. having a circle with a purpose
2. having all tensions coming from roles of that circle, roles with purposes
3. having max 10-12 ppl in a governance meeting


The holacracy way would be to give these domains to a role or a circle. For example so TLC governance would decide on these domains.

**Comment by cassus** [comment]
The other option I see that is more within the Holacracy framework is to delegate the _Salary formula_ and _Ownership system_ domains to a circle eg. TLC and have them decide with the circle's governance process. If any tension comes up anywhere in the company ppl can direclty advise TLC role holders or channel the tension through RepLinks.

**Comment by cassus** [comment]
Note to Secretary: pls don't auto-merge this even if 3 days pass. I'd like to take advice from many ppl. before I officially propose this (= WIP = Work In Progress in the title)

**Comment by peterlangmar** [comment]
I fully share the tension regarding some decisions (salary, social responsibility, legal framework of the org etc), but I do not agree with the solution. I think the implementation could end creating more chaos than relief.

In my opinion the proposed solution it is too early and your reasoning can be questioned, because:
- circles still don't have purposes
- roles' domains are still not defined (domain, acco, 
- the use of holacracy is still not a real practice, even not in TLC

However, I can agree more with your comment: "The other option I see that is more within the Holacracy framework is to delegate the _Salary formula_ and _Ownership system_ domains to a circle eg. TLC and have them decide with the circle's governance process. If any tension comes up anywhere in the company ppl can direclty advise TLC role holders or channel the tension through RepLinks."

Example: It is like trying to push TDD to a basic WorldPress user.

Case: Just because you are comfortable with these processes does not implicate that the whole organization can adopt them that fast. We can not just copy paste a process into our governance. This is what I've expressed regarding the conflict resolution process policy too. Please, remember, how long the road has already been with holacracy and here are we with it (far, but not far enough). You, as a professional org dev have well prepared and soft landed holacracy. In a weaker way, but NVC practice helped some of us to be able to use the conflict resolution process. In case of the advice process we also need something like that. Better deep, rather than fast.

My proposition: I'd have endless objections against 'any partner can make any decision', but would consider the usage  of the advice process in a different way.
1. Lets clarify the domain of each role and circle, which would indicate who's call that decision should be. Dedicate these critical decisions to roles and / or circles. Will happen at team retreat. (If you have read this far I owe you a lunch. Come to me and say: I like the smell of burning napalm early in the morning.) 2. The advising process should be the responsibility of the role / circle which's domain those company wide decisions are. These roles have already been using an informal advising process just remember how @cassus interviewed everybody regarding the first salary formula iterations. This way we do not have to implement the advice process in general, moreover we do not end up in the chaos of 'any partner can make any decision'.

**Comment by nagydan1** [comment]
Noted

**Comment by cassus** [comment]
@nagydan1 what do you mean by _Noted_?

**Comment by nagydan1** [comment]
@cassus noted the comment "Note to Secretary: pls don't auto-merge this even if 3 days pass. I'd like to take advice from many ppl. before I officially propose this (= WIP = Work In Progress in the title)"

**Comment by cassus** [comment]
I see! thx

**Comment by peterlangmar** [comment]
@cassus both the propositions would mean the end of the company wide circle with the existing domain, right? The general corporate assembly would be something similar, but legally binding, however having different domain as per in the legal docs.

**Comment by peterlangmar** [comment]
ps: My 'how much you care' test is over: only three people @hubudibu @cassus and @judikdavid have read my policy comment in 3 days in case of a company wide topic. The four of us should schedule a lunch for the next two weeks, the tab is on me.

**Comment by cassus** [comment]
Yes, both propositions would end of the company wide circle with the current domain and decision un-process.

One would move the domain to different circles.
The other one would keep the CompanyWide circle but change the decision making process.

The corporate assembly will only make high level decisions like appointing the TLC LL, extra dividend pay, maybe some big strategy decisions.
We shouldn't vote on salary system changes... especially not based on ownership ratios.

**Comment by nagydan1** [comment]
:) Bon apetit

**Comment by peterlangmar** [comment]
@cassus I full agree with your last comment

**Comment by EggDice** [comment]
Haha! TL;DR I started to read it but it was more than 3 paragraph :D

**Comment by cassus** [comment]
Some decisions take more than a tweet worth of information to consider :P

**Comment by peterlangmar** [comment]
we are just about to implement a policy which will allow others not to read such a long text / invest time into governance if they are not willing to

**Comment by cassus** [comment]
CompanyWide decided today that HR circle shall have the domain of Salary Formula and System.

**Comment by peterlangmar** [comment]
the rest of the company wide domains should be distributed between different roles too

**Comment by cassus** [comment]
I agree but I have the need to take care of my other responsibilities first.

**Comment by peterlangmar** [comment]
at next meeting we should discuss this

**Comment by peterlangmar** [comment]
@cassus will you bring this to TLC?

**Comment by cassus** [comment]
a new version, next week

**Comment by cassus** [comment]
Feel free to bring your own tensions, proposals related to this

**Comment by cassus** [comment]
Resolved by 0941e669def411abc8dff69b708bad4f948541c9

**Pull request closed without merging**
