### PR TITLE
growing business

### PR DESCRIPTION
**Pull request by peterlangmar**
Tension: was unclear for PP, if driving the grow of the business

### CODE REVIEW

**Comment by kire321** [comment]
:question: What does "Facilitating growing business" mean?

**Comment by peterlangmar** [comment]
I've updated to 'facilitating business growth'. clear now?
context: this role is the business mindset and the role has been asked before about growth plan etc.

please, notify secretary, if the questions has been answered

**Comment by kire321** [comment]
`facilitating business growth` could mean anything. More specific accountablities would be more useful.
:question: Please bring to gov

**Comment by peterlangmar** [comment]
Why exactly?

**Pull request closed without merging**
