### PR TITLE
No part time if making money

### PR DESCRIPTION
**Pull request by peterlangmar**
Virag's, Feri's and Deme Dani's examples show it clearly, that two paid part-time things at the same time is just not working and harms the company.

### CODE REVIEW

**Comment by cassus** [comment]
It would be better if you state the end of the 3 months, so we won't have to dig logs to figure out when it ends

**Comment by peterlangmar** [comment]
@cassus I do not understand your comment. Please, rephrase your suggestion.

**Comment by cassus** [comment]
> For the existing part-time Partners with for-profit / for-equity side projects / work there is a 3 month grace / transition period.

It will be hard to know in 3 months when exactly those 3 months are over. It's better if you give a date

**Comment by peterlangmar** [comment]
ack

**Comment by cassus** [comment]
accepted in governance

**Pull request closed without merging**
